### ISSUE TITLE
Can we send private transaction with out data field?

### ISSUE THREAD

**Issue by nandakishorebhandari** [jpmorganchase/quorum-acceptance-tests#2]
In file 
 https://github.com/jpmorganchase/quorum-acceptance-tests/blob/master/functional-tests/acceptance-test/private_txn_test.js

Saw this line:
`  var txHash = await eth.sendTransaction({from:fromAcct,to:toAcct,value:amount, privateFor:[constellationId]})`

When I try to test the same like below:

`jsonrpc: '2.0',
  id: 4,
  method: 'bxm_sendTransaction',
  params:
   [ { from: '0x4995df9035398fa42685a3ecb595f472002263b4',
       to: '0x0e53b32bc0bb62742678d6c3997a672d55c3b748',
       value: '0x0',
       privateFor: [Array],
       gasPrice: '0x0' } ] }`

I get following error

`10:05:32 [WARN] Failed to decode '/send' (POST) request: Error in $.payload: base64: input: invalid length
`

What is expected if we send value 0 in private transaction without data field?
What is expected if we send the value like 10 in private transaction without data field?

Based on this [issue](https://github.com/jpmorganchase/quorum/issues/528), 
For any value (either 0 or some value) transfee private transaction, the error message "ether value is not supported for private transactions" should be thrown.

**Comment by nandakishorebhandari** [comment]
I found this in the quorum, its check for length of data. 

If data is available, consider it as a private transaction or else perform the public transaction. If this is right then why are we sending privateFor field in value transaction?

	if len(data) > 0 {
			log.Info("sending private tx", "data", fmt.Sprintf("%x", data), "privatefrom", args.PrivateFrom, "privatefor", args.PrivateFor)
			data, err = private.P.Send(data, args.PrivateFrom, args.PrivateFor)
			log.Info("sent private tx", "data", fmt.Sprintf("%x", data), "privatefrom", args.PrivateFrom, "privatefor", args.PrivateFor)
			if err != nil {
				return common.Hash{}, err
			}
		} // else tx_pool.go#validateTx will capture and throw error
		args.Data = data

**Comment by trung** [comment]
@nandakishorebhandari yes, currently Quorum does not support value transfer transactions.
[Here](https://jpmorganchase.github.io/quorum-acceptance-tests/docs/html/src/specs/01_basic/value_transfer_private_transactions.html) is the specification for that. And [here](https://jpmorganchase.github.io/quorum-acceptance-tests/istanbul/reports/html-report/src/specs/01_basic/value_transfer_private_transactions.html) is the correspending test report.
